name: 'Bridge Tests'

on:
  schedule:
    - cron:  '0 7,15,22 * * *'
    # scheduled at 07, 15 and 22 every day

  workflow_dispatch:  # click the button on Github repo!

jobs:
  test-bridges:
    name: Test Bridges
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2.3.2
      - name: Start docker
        run: |
          echo "*" > /home/runner/work/rss-bridge-tester/rss-bridge-tester/whitelist.txt;
          docker run -d -v /home/runner/work/rss-bridge-tester/rss-bridge-tester/whitelist.txt:/app/whitelist.txt -p 3000:80 ghcr.io/rss-bridge/rss-bridge:latest
      - name: Sleep for 5 seconds
        run: sleep 5s
        shell: bash
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          cache: 'pip'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run bridge tests
        run: python bridgetester.py
      - name: Update deployment files
        uses: test-room-7/action-update-file@v1
        with:
          file-path: stats.csv
          commit-msg: New run
          github-token: ${{ secrets.GITHUB_TOKEN }}